---
- name: Install Docker on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      become: yes

        #    - name: Create /etc/apt/keyrings directory
        #      file:
        #        path: /etc/apt/keyrings
        #        state: directory
        #        mode: '0755'

    - name: Add Docker's GPG key
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
      become: yes

    - name: Set up the stable Docker repository
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        create: yes
      become: yes


          #    - name: Download Docker GPG key
      #      get_url:
        #        url: https://download.docker.com/linux/ubuntu/gpg
          #        dest: /etc/apt/keyrings/docker.asc
          #        mode: '0644'

          #    - name: Add Docker APT repository
          #      apt_repository:
          #        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
          #        state: present

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present


    - name: Add user to docker group
      shell: "usermod -a -G docker $USER"
      become: yes

    - name: switch user to make the change happen
      shell: "su - $USER"
      become: yes


#    - name: Add your user to the Docker group
#      user:
#        name: "{{ ansible_facts.user_id }}"
#        groups: docker
#        append: yes

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted
        enabled: yes

    - name: Test Docker installation
      command: docker --version
